version: "3.7"

services:
 nginx:
  container_name: nginx
  build: ./requirements/nginx/
  image: nginx:inception
  ports:
   - "443:443"
  depends_on:
   - wordpress
  volumes:
   - wp_data:/var/www
  env_file:
   - .env
  networks:
   - inception_net
  restart: always

 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress/
  image: wordpress:inception
  depends_on:
   - mariadb
  volumes:
   - wp_data:/var/www
  networks:
   - inception_net
  env_file:
   - .env
  restart: always

 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb/
  image: mariadb:inception
  volumes:
   - db_data:/var/lib/mysql
  networks:
   - inception_net
  env_file:
   - .env
  restart: always

volumes:
 wp_data:
  name: wp_data
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/tfinni/data/wordpress

 db_data:
  name: db_data
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/tfinni/data/mariadb

networks:
 inception_net:
  name: inception_net
  driver: bridge